import {
  Activity,
  ClipboardCheck,
  FileStack,
  GitBranch,
  Landmark,
  Microscope,
  Network,
  Scale,
  ShieldCheck,
  SquareKanban,
} from "lucide-react";

export const lifecycle = [
  "Question",
  "Protocol",
  "Retrieval",
  "Evidence Map",
  "Human Review",
  "Extraction",
  "Validation",
  "Report",
  "Audit",
];

export const modules = [
  {
    id: "precision_literature_review",
    slug: "systematic-literature-review",
    displayName: "Precision Literature Review",
    shortName: "Precision SLR",
    mappedSkill: "pharma-slr",
    status: "connected skill",
    publicRoute: "/solutions/systematic-literature-review",
    workspaceRoute: "/workspace/modules/precision-slr",
    icon: Microscope,
    oneLiner:
      "Precision-controlled systematic literature review for biomedical evidence teams.",
    headline: "Control recall, precision, and screening burden.",
    users: ["Evidence generation", "Medical affairs", "HEOR", "Regulatory"],
    workflow: [
      "PICO/PECO protocol",
      "Concept expansion",
      "Multi-source retrieval",
      "Deduplication",
      "Precision scoring",
      "Screening and adjudication",
      "Evidence extraction",
      "PRISMA and validation",
    ],
    artifacts: [
      "Protocol",
      "Search strategy",
      "Evidence map",
      "Screening queue",
      "Evidence table",
      "PRISMA summary",
      "Validation report",
      "Audit trail",
    ],
    guardrails: [
      "Fixture smoke tests are not validation evidence.",
      "AI screening is not final without human review.",
      "Precision controls must preserve recall guardrails.",
    ],
    demoProject: "demo_dupilumab_ad_slr",
  },
  {
    id: "heor_evidence_modeler",
    slug: "heor",
    displayName: "HEOR Evidence Modeler",
    shortName: "HEOR Modeler",
    mappedSkill: "heor-evidence-modeler",
    status: "connected skill",
    publicRoute: "/solutions/heor",
    workspaceRoute: "/workspace/modules/heor",
    icon: Activity,
    oneLiner:
      "Traceable model-input preparation for HEOR teams and health economists.",
    headline: "Prepare traceable HEOR model inputs for expert review.",
    users: ["HEOR", "Market access", "Health economics"],
    workflow: [
      "Model scope",
      "Evidence needs",
      "Input extraction",
      "Evidence map",
      "Assumption register",
      "Evidence readiness",
      "Health economist review",
      "Validation and audit",
    ],
    artifacts: [
      "Model scope",
      "Model input table",
      "Evidence map",
      "Assumption register",
      "Evidence readiness",
      "Review queue",
      "Audit trail",
    ],
    guardrails: [
      "No final ICER, QALY, or budget impact claims without a validated model.",
      "Missing input values remain assumption flags.",
      "Every input needs provenance, uncertainty, or an assumption flag.",
    ],
    demoProject: "demo_dupilumab_heor_inputs",
  },
  {
    id: "payer_value_dossier",
    slug: "payer-value-dossier",
    displayName: "Payer Value Dossier Builder",
    shortName: "Payer Dossier",
    mappedSkill: "payer-value-dossier-builder",
    status: "connected skill",
    publicRoute: "/solutions/payer-value-dossier",
    workspaceRoute: "/workspace/modules/payer-value-dossier",
    icon: Landmark,
    oneLiner:
      "Evidence-traceable payer dossier preparation for market access teams.",
    headline: "Build payer evidence packages with claim traceability.",
    users: ["Market access", "HEOR", "Medical affairs"],
    workflow: [
      "Dossier scope",
      "Evidence blocks",
      "Claim traceability",
      "Evidence map",
      "Gap check",
      "Market access review",
      "Dossier draft",
      "Validation and audit",
    ],
    artifacts: [
      "Dossier scope",
      "Claim traceability matrix",
      "Evidence map",
      "Dossier gap check",
      "Value dossier draft",
      "Audit trail",
    ],
    guardrails: [
      "No payer decision, formulary, or pricing predictions.",
      "Unsupported claims remain flagged.",
      "Economic claims must be sourced, modeled, or labeled as assumptions.",
    ],
    demoProject: "demo_dupilumab_payer_dossier",
  },
  {
    id: "regulatory_evidence_briefing",
    slug: "regulatory-briefing",
    displayName: "Regulatory Evidence Briefing",
    shortName: "Regulatory Briefing",
    mappedSkill: "regulatory-evidence-briefing",
    status: "connected skill",
    publicRoute: "/solutions/regulatory-briefing",
    workspaceRoute: "/workspace/modules/regulatory-briefing",
    icon: Scale,
    oneLiner:
      "Conservative, traceable regulatory evidence briefings for strategy teams.",
    headline: "Structure benefit-risk evidence conservatively.",
    users: ["Regulatory affairs", "Clinical strategy", "Medical writing"],
    workflow: [
      "Regulatory context",
      "Precedent and evidence review",
      "Benefit-risk table",
      "Evidence map",
      "Uncertainty register",
      "Language guardrail",
      "Regulatory review",
      "Briefing and audit",
    ],
    artifacts: [
      "Regulatory context",
      "Benefit-risk table",
      "Evidence map",
      "Uncertainty register",
      "Language guardrail",
      "Regulatory briefing",
      "Audit trail",
    ],
    guardrails: [
      "No regulatory approval predictions.",
      "Evidence, uncertainty, and interpretation stay separate.",
      "No safety or efficacy proof language without validated support.",
    ],
    demoProject: "demo_dupilumab_regulatory_briefing",
  },
  {
    id: "drug_repurposing_explorer",
    slug: "drug-repurposing",
    displayName: "Drug Repurposing Evidence Explorer",
    shortName: "Repurposing Explorer",
    mappedSkill: "drug-repurposing-evidence-explorer",
    status: "connected skill",
    publicRoute: "/solutions/drug-repurposing",
    workspaceRoute: "/workspace/modules/drug-repurposing",
    icon: Network,
    oneLiner:
      "Graph-assisted repurposing hypothesis exploration with clinician review guardrails.",
    headline:
      "Rank repurposing hypotheses through disease similarity, safety signals, and transparent evidence paths.",
    users: ["R&D strategy", "Translational science", "Business development"],
    workflow: [
      "Mode detection",
      "Entity and relation extraction",
      "Knowledge graph build",
      "Disease similarity support",
      "Candidate link scoring",
      "Indication and contraindication separation",
      "Method-family signal comparison",
      "False-positive and false-negative risk checks",
      "Safety transfer assessment",
      "Evidence path explanation",
      "Explanation review queue",
      "Scientific review",
      "Validation checklist and audit",
    ],
    artifacts: [
      "Knowledge graph",
      "Candidate links",
      "Zero-shot hypothesis ranking",
      "Method evidence matrix",
      "False-positive and false-negative risk report",
      "Evidence path explanation",
      "External usage signal review",
      "Safety transfer assessment",
      "Validation checklist",
      "Audit trail",
    ],
    guardrails: [
      "No therapy recommendations.",
      "Graph paths are not causal proof.",
      "Research papers become governed method signals, not product proof.",
      "External usage signals are treated as confounded review inputs, not validation.",
      "Every candidate remains hypothesis-only until reviewed and validated.",
    ],
    demoProject: "demo_dupilumab_repurposing_graph",
  },
];

export const governanceModule = {
  displayName: "Evidence Governance & Validation Layer",
  shortName: "Governance",
  mappedSkill: "shared governance scripts across EvidenceOS skills",
  status: "connected skill",
  publicRoute: "/governance",
  workspaceRoute: "/workspace/validation",
  icon: ShieldCheck,
  oneLiner:
    "Human review, validation, and audit controls across EvidenceOS evidence workflows.",
  workflow: [
    "Human review queue",
    "Reviewer decision capture",
    "Adjudication or override",
    "Validation report",
    "Audit trail",
    "Project manifest",
  ],
  controls: [
    "Structured reviewer queues",
    "Dual-reviewer adjudication",
    "Validation reports",
    "Audit metadata",
    "Fixture-only warnings",
    "Project manifests",
  ],
};

export const demoProjects = [
  {
    id: "demo_dupilumab_ad_slr",
    moduleId: "precision_literature_review",
    title: "Dupilumab in Atopic Dermatitis: Precision SLR Demo",
    status: "fixture ready",
    artifactCount: 5,
  },
  {
    id: "demo_dupilumab_heor_inputs",
    moduleId: "heor_evidence_modeler",
    title: "Dupilumab HEOR Model Inputs Demo",
    status: "fixture ready",
    artifactCount: 4,
  },
  {
    id: "demo_dupilumab_payer_dossier",
    moduleId: "payer_value_dossier",
    title: "Dupilumab Payer Value Dossier Demo",
    status: "fixture ready",
    artifactCount: 4,
  },
  {
    id: "demo_dupilumab_regulatory_briefing",
    moduleId: "regulatory_evidence_briefing",
    title: "Dupilumab Regulatory Evidence Briefing Demo",
    status: "fixture ready",
    artifactCount: 4,
  },
  {
    id: "demo_dupilumab_repurposing_graph",
    moduleId: "drug_repurposing_explorer",
    title: "Dupilumab Zero-Shot Repurposing Evidence Graph Demo",
    status: "fixture ready",
    artifactCount: 8,
  },
];

export const platformStats = [
  { label: "Product modules", value: "5" },
  { label: "Governance layer", value: "1" },
  { label: "Fixture demos", value: "5" },
  { label: "Audit mode", value: "On" },
];

export const visualNodes = [
  { label: "Protocol", icon: ClipboardCheck, x: "8%", y: "18%" },
  { label: "Retrieval", icon: GitBranch, x: "34%", y: "9%" },
  { label: "Evidence Map", icon: Network, x: "63%", y: "20%" },
  { label: "Human Review", icon: SquareKanban, x: "16%", y: "64%" },
  { label: "Validation", icon: ShieldCheck, x: "49%", y: "70%" },
  { label: "Report", icon: FileStack, x: "75%", y: "58%" },
];

export type EvidenceModule = (typeof modules)[number];
